const GET_QUESTIONS = 'GET_QUESTIONS';
const UPDATE_SEARCH_PARAMS = 'UPDATE_SEARCH_PARAMS';
const UPDATE_PAGINATION = 'UPDATE_PAGINATION';
const UPDATE_SORT = 'UPDATE_SORT';

export { GET_QUESTIONS, UPDATE_SEARCH_PARAMS, UPDATE_PAGINATION, UPDATE_SORT };
